version: '3'

services:
  api:
    build: .
    volumes:
      # Mount our code base so changes are propagated
      - .:/opt/titanic-api
      # Virtually unmount the node_modules directory, to keep local and in-docker separate
      # This is necessary especially with node modules, which need to be built for different architectures (local & docker)
      # Propagating node_modules would break in-docker binaries with local versions
      - /opt/titanic-api/node_modules
    ports:
      - 3000:3000
  tests:
    build:
      context: .
      target: local
    image: chriscmsoft/titanic-api:local
    command: ["npm", "run", "test:watch"]
    volumes:
      - .:/opt/titanic-api
      - /opt/titanic-api/node_modules
